name: docker

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build backend
        run: docker build -f ./docker/Backend . -t ghcr.io/marcorfilacarreras/duplicati-dashboard:backend
      
      - name: Push
        run: docker push ghcr.io/marcorfilacarreras/duplicati-dashboard:backend

      - name: Build frontend
        run: docker build -f ./docker/Backend . -t ghcr.io/marcorfilacarreras/duplicati-dashboard:frontend
      
      - name: Push
        run: docker push ghcr.io/marcorfilacarreras/duplicati-dashboard:frontend