name: docker

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**/README.md'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build backend
        run: docker buildx build --push -t ghcr.io/marcorfilacarreras/duplicati-dashboard:backend --platform linux/arm/v7,linux/arm64,linux/amd64 --file docker/Backend .

      - name: Build frontend
        run: docker buildx build --push -t ghcr.io/marcorfilacarreras/duplicati-dashboard:frontend --platform linux/arm/v7,linux/arm64,linux/amd64 --file docker/Frontend .
